while True:
    print()
    print("More Than, Less Than, Equals Too")
    print()
    var1=input(int())
    var2=input(int())
    print(var1)
    print(var2)
    print()
    if (var1==var2): print ("equal")
    if (var1>var2): print (var1, ">" ,var2)
    if (var1<var2): print(var1, "<" ,var2)